version: '3'
services:
  usertest: # 컨테이너1 :
    container_name: user
    build:
      context: ./user-service/
      dockerfile: Dockerfile
    depends_on:
      - discovery
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE : http://discovery:6001/eureka
    networks:
      - msa_test

  discovery: # 컨테이너2 :
    container_name: discovery
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6001:6001"
    networks:
      - msa_test

  gateway: # 컨테이너2 :
    container_name: gateway
    build:
      context: ./testgate/
      dockerfile: Dockerfile
    ports:
      - "80:6005"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:6001/eureka
    depends_on:
      - discovery
    networks:
      - msa_test
networks:
  msa_test:
    driver: bridge
