server:
  port: 5001

spring:
  application:
    name: discoveryservice
eureka:
  client:
    # ??? ??? ??? ??? ???? ???.
    register-with-eureka: false
    # defaultZone? ??? ???? ????? ??? ?????.
    fetch-registry: false
