server:
  port: 5001

spring:
  application:
    name: discoveryservice
  cloud:
    uri: http://127.0.0.1:8888
    name: msa
eureka:
  client:
    # ??? ??? ??? ??? ???? ???.
    register-with-eureka: false
    # defaultZone? ??? ???? ????? ??? ?????.
    fetch-registry: false
    # server: #????? ????
    # enable-self-preservation: false #????? ??, ??? ?????
    # eviction-interval-timer-in-ms: 3000 #???? ????
    service-url:
      defaultZone: http://127.0.0.1:5001/eureka
